# Generated by Django 4.0 on 2022-02-23 21:16

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_myuser_is_active'),
        ('blog', '0002_alter_blog_options_alter_blog_author_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(help_text='Enter comment about blog here.', max_length=1000, verbose_name="blog's comment")),
                ('comment_date', models.DateTimeField(default=datetime.datetime.now, verbose_name="comment's date")),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.myuser', verbose_name="author's comment")),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.blog', verbose_name="blog's resource")),
            ],
            options={
                'ordering': ['comment_date'],
            },
        ),
    ]
