# Generated by Django 4.0 on 2022-02-23 22:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_blogcomment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='post_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name="blog's posted date"),
        ),
        migrations.AlterField(
            model_name='blogcomment',
            name='comment_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name="comment's date"),
        ),
    ]
