# Generated by Django 4.0 on 2022-05-06 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_blog_author_alter_blog_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to='blog_cover_images/', verbose_name='cover image'),
        ),
    ]
