# Generated by Django 4.0 on 2022-04-01 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_myuser_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='bio',
            field=models.TextField(blank=True, null=True, verbose_name='bio'),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True, verbose_name='birthdate'),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='name',
            field=models.CharField(max_length=150, verbose_name='username'),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='profile picture'),
        ),
    ]
